istio:
  monitoring:
    namespace: 'istio-system'
    namespaceSelector:
      any: true
  gateway:
    namespace: 'istio-system'
    virtualservice:
      grafana:
        hosts:
          - 'grafana.${domain}'
        http:
          - name: 'grafana'
            route:
              - destination:
                  port:
                    number: 3000
                  host: grafana.operations.svc.cluster.local
      webui:
        hosts:
          - 'webui.${domain}'
        http:
          - name: 'webui'
            route:
              - destination:
                  port:
                    number: 80
                  host: open-webui.llm.svc.cluster.local

certmanager:
  namespace: 'operations'
  email:
    - ${email}
  # staging: false

certificate:
  dnsNames:
    - "*.${domain}"

kiali-server:
  external_services:
    tracing:
      enabled: false
    grafana:
      enabled: true
      in_cluster_url: http://grafana.operations.svc.cluster.local:3000
    prometheus:
      url: http://prometheus-kube-prometheus-prometheus.operations.svc.cluster.local:9090
