istio:
  monitoring:
    namespace: 'istio-system'
    namespaceSelector:
      any: true
  gateway:
    namespace: 'istio-system'
    virtualservice:
      hosts:
        - ${domain}
      http:
        - name: 'grafana'
          match:
            - uri:
                prefix: /grafana
          route:
            - destination:
                port:
                  number: 3000
                host: grafana.operations.svc.cluster.local
        - name: 'webui'
          match:
            - uri:
                prefix: /webui
          rewrite:
            uri: /
          route:
            - destination:
                port:
                  number: 80
                host: open-webui.llm.svc.cluster.local

certmanager:
  namespace: 'operations'
  email:
    - ${email}
  # staging: false

certificate:
  dnsNames:
    - ${domain}

kiali-server:
  external_services:
    tracing:
      enabled: false
    grafana:
      enabled: true
      in_cluster_url: http://grafana.operations.svc.cluster.local:3000
    prometheus:
      url: http://prometheus-kube-prometheus-prometheus.operations.svc.cluster.local:9090
