resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
tolerations:
  - operator: Exists
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Exclude_Path /var/log/containers/*_istio-proxy*,/var/log/containers/*_istio-init*,/var/log/containers/cloudwatch-agent*,/var/log/containers/fluent-bit*,/var/log/containers/aws-node*,/var/log/containers/kube-proxy*,/var/log/containers/*kafka-controller*
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On
        Read_from_Head On
    [INPUT]
        Name tail
        Path /var/log/containers/*kafka-controller*
        multiline.parser docker, cri
        Tag kafka.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On
        Read_from_Head On

  filters: |
    [FILTER]
        Name parser
        Match kafka.*
        Parser kafka_parser
        Key_Name log
        Reserve_Data True

    [FILTER]
        Name kubernetes
        Match kafka.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *
        region ${region}
        log_group_name /aws/containerinsights/${cluster_name}/application
        log_stream_prefix application-
        auto_create_group true
        extra_user_agent container-insights
        workers 1

  customParsers: |
    [PARSER]
        Name kafka_parser
        Format regex
        Regex \[(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\] (?<level>[A-Z]+) (?<message>.+?) \((?<logger>[^\)]+)\)
        Time_Key time
        Time_Format %Y-%m-%d %H:%M:%S,%L
