replicaCount: 1
db:
  config:
    host: 'postgresql.postgresql.svc.cluster.local'
    port: '5432'
env:
  KAFKA_BROKERS: 'kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092'
  KAFKA_SERVICE: 'kafka.kafka.svc.cluster.local'
  KAFKA_TOPIC: 'cve'
  PORT: '3001'
  LLAMAINDEX_OLLAMA_BASE_URL: 'http://open-webui-ollama.llm.svc.cluster.local:11434'
  KAFKA_CONSUMER_GROUP_ID: 'ingestor'
  LLAMAINDEX_EMBEDDING_MODEL_NAME: 'nomic-embed-text:v1.5'
  EMBEDDING_DIM: '768'
  DB_TABLE: 'embeddings'
resources:
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPU: 5
    targetMemory: 5
    annotations: {}
