ollama:
  enabled: true
  fullnameOverride: 'open-webui-ollama'
  ollama:
    gpu:
      enabled: true
      type: 'nvidia'
      number: 1
    models:
      - gemma:2b
      - mxbai-embed-large:latest
  resources:
    requests:
      memory: 4096Mi
      cpu: 2000m
    limits:
      memory: 7000Mi
      cpu: 3500m
  persistentVolume:
    enabled: true
  tolerations:
    - key: 'nvidia.com/gpu'
      operator: 'Exists'
      effect: 'NoSchedule'
pipelines:
  enabled: true
  image:
    repository: marlapativ/pipelines
    tag: v1.2.1
    pullPolicy: Always
  tolerations:
    - key: 'nvidia.com/gpu'
      operator: 'Exists'
      effect: 'NoSchedule'
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
tolerations:
  - key: 'nvidia.com/gpu'
    operator: 'Exists'
    effect: 'NoSchedule'
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
